name: release

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  test_boost:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Install boost
        uses: MarkusJx/install-boost@v2.0.0
        id: install-boost
        with:
          boost_version: 1.77.0
          platform_version: 20.04
          boost_install_dir: /home/runner/
      
      - name: ls
        run: |
          ls /home/runner/boost/boost
          ls /home/runner/boost/boost/include
          ls /home/runner/boost/boost/lib