name: release

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  test_boost:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: install
        run: |
          brew install xmake
          xmake update deb
          brew install open-mpi
          brew install boost
          brew install boost-mpi
          export LD_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/Cellar/boost-mpi/1.76.0/lib:$LD_LIBRARY_PATH
          export LD_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/Cellar/boost/1.76.0/lib:$LD_LIBRARY_PATH
      
      - name: ls
        run: |
          ls /home/linuxbrew/.linuxbrew/Cellar/boost-mpi/1.76.0/lib
          echo hello
          ls /home/linuxbrew/.linuxbrew/Cellar/boost/1.76.0/lib
          echo hello
          echo $LD_LIBRARY_PATH