name: release

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install xmake
        run:  brew install xmake


      - name: Install packages
        run: |
          brew install openmpi
          brew install boost
          brew install boost-mpi
        
      - name: Build the target
        run: |
          xmake l find_packages cmake::Boost
          xmake l find_packages cmake::MPI